# File: render.yaml

services:
  - type: web
    name: inventory-management-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGODB_URI
        fromDatabase: kiminventoryDB
      - key: JWT_SECRET
        value: mysupersecretkey123!@

  - type: web
    name: inventory-management-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
